services:
  trip-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=trip-api'
      - 'POSTGRES_USER=trip-api'
      - 'POSTGRES_PASSWORD=trip-api'
    ports:
      - '65432:5432'
  trip-api:
    image: 'trip-api:0.0.1-SNAPSHOT'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://trip-db:5432/trip-api
      SPRING_DATASOURCE_USERNAME: trip-api
      SPRING_DATASOURCE_PASSWORD: trip-api
    ports:
      - '8888:8080'
    platform: 'linux/amd64'

