services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=trip-api'
      - 'POSTGRES_USER=trip-api'
      - 'POSTGRES_PASSWORD=trip-api'
    ports:
      - '65432:5432'
