-- Insert into TRIP_TYPE
INSERT INTO TRIP_TYPE (ID, NAME) VALUES (1, 'Type 1');
INSERT INTO TRIP_TYPE (ID, NAME) VALUES (2, 'Type 2');

-- Insert into TRIP
INSERT INTO TRIP (ID, NAME, DISCOUNT, TYPE_ID, LINK, DESCRIPTION, PERFORMANCE, ADDITIONAL_INFO, VALIDITY, PRICE)
VALUES (1, 'Trip 1', 0, 1, 'Link 1', 'Description 1', 'Performance 1', 'Additional Info 1', 'valid on bla bla', 100.0);

INSERT INTO TRIP (ID, NAME, DISCOUNT, TYPE_ID, LINK, DESCRIPTION, PERFORMANCE, ADDITIONAL_INFO, VALIDITY, PRICE)
VALUES (2, 'Trip 2', 50, 2, 'Link 2', 'Description 2', 'Performance 2', 'Additional Info 2', 'valid on blub', 200.0);

-- Insert into TRIP_BOOKING
INSERT INTO TRIP_BOOKING (ID, BOOKING_DATE, TRIP_ID) VALUES (1, '2022-03-01', 1);
INSERT INTO TRIP_BOOKING (ID, BOOKING_DATE, TRIP_ID) VALUES (2, '2022-03-02', 1);
INSERT INTO TRIP_BOOKING (ID, BOOKING_DATE, TRIP_ID) VALUES (3, '2022-03-03', 2);
